[package]
name = "gucci_lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
serial_test = "*"

[dependencies]
ariadne = "0.1.5"
chumsky = "0.8.0"
lazy_static = "1.4.0"
